### ISSUE TITLE
A little note on the game-play balance

### ISSUE THREAD

**Issue by Kerollmops** [facundoolano/rpg-cli#102]
- We gain just a little too much gold in late games (3150360g on this 1h game).
 - Are lvl-stone effects skipped for achievements? Is an +event raised when a stone is used?
 - We maybe should use a seed-based RNG based on the path to knowing if we must generate a new boss, it is easy to just go to the same 3/4 paths to fight something and gain XP without endangeringyourself.

**Comment by facundoolano** [comment]
Thanks for all this feedback, it's really helpful since I've been focusing in new features lately and haven't stressed the gameplay and balance much, particularly I haven't reached high levels. I leave some questions below.

Are you playing with the code in main or a tagged version?

> We gain just a little too much gold in late games (3150360g on this 1h game).

It's likely that the current balance is not right. Can you give me more details about your session? what level have you reached? are you playing far from home? do you easily beat the enemies?

> Are lvl-stone effects skipped for achievements? Is an +event raised when a stone is used?

Do you mean that the "reach level N" quests are ignoring the level increases from stones? If that's the case it's a bug, probably not emitting the proper event.

> We maybe should use a seed-based RNG based on the path to knowing if we must generate a new boss, it is easy to just go to the same 3/4 paths to fight something and gain XP without endangeringyourself.

Can you elaborate? I haven't stressed this approach of not going far from home. My goal would be to have a balance such that after you reach a certain level it just doesn't pay off to stay close to home; the gained xp and leveling formula probably need to be tuned in this direction.

**Comment by facundoolano** [comment]
The level stone issue is addressed in https://github.com/facundoolano/rpg-cli/pull/103

**Comment by Kerollmops** [comment]
> Are you playing with the code in main or a tagged version?

I was playing using my fork that starts from the main branch.

> Can you give me more details about your session? what level have you reached? are you playing far from home?

I can probably be considered a cheater, I was spamming a "go to the first two depths and come back" technic, it is very safe when you got a sword[5] and shield[5] and you get so much stuff/gold and earn so much experience in comparison to the no-risk exploration.

I also found it quite complex to go to a depth 10 but that's the game, in fact, I had to create further folders to find legendary creatures, and due to the fact that going back and forth one folder makes it generate new random combats, it was easy to just use the cheating trick to find all of the creatures to complete my quest. The deepest folder I found in my documents was of depth 8 and was deep in the target folder of a big rust repository, but don't change that, it seems pretty ok in fact.

```bash
# just going to the first two depths and come back home, going home heal you then.
for f in */*(/); do rpg cd $f && ls && rpg cd; done;
```

Here is the level reached by using the cheating trick above.

```
thief[75]@home
    hp:[xxxxxxxxxx] 992/992
    mp:[----------] 0/0
    xp:[xxxxxxxxx-] 16572/19485
    att:534   mag:0   def:117   spd:668
    equip:{sword[100],shield[75]}
    item:{escapex115,etherx462,mp-stonex89,potionx2143,remedyx133}
    4554557g
```

> do you easily beat the enemies?

Yes, as I always hit the mob first I kill in one sword hit. I suppose it is due to my high speed?

> Can you elaborate? I haven't stressed this approach of not going far from home. My goal would be to have a balance such that after you reach a certain level it just doesn't pay off to stay close to home; the gained xp and leveling formula probably need to be tuned in this direction.

What I want to say here was that the game doesn't really know the places you already explore and therefore just going back and forth makes the dungeon be generated again. A, maybe simple-enough technic, would be to save the paths that were already explored somewhere and with the help of a TTL system regenerate the dungeon after some time. It would balance a little bit more the low-level cheating technic I was using. Also, this technic should be used for the gold and stuff found with an `ls`, this must also be balanced.

Keeping track of the path explored by the player would also force him to explore more than the two first depths. It is not mandatory to keep track of the whole path explored, it can be only the last 100/1000 paths.

**Comment by facundoolano** [comment]
Great. I'll think some more about this and will try to make some improvements before the next release.

**Comment by facundoolano** [comment]
I've been making some tweaks and fixes trying to improve the balance. Specifically there were two issues that directly contributed to the issues described here: the gold found on chests was too high, and the xp gained was based in the attacker strength rather than in the receiver hp (that is, the stronger the hero, the higher xp reward). Now it's harder go raise the level by staying close to the home dir.

@Kerollmops (or anyone else looking at this): if you have time I'd be interested to hear how the latest version looks in terms of balance and difficulty for you. I'm not particularly interested in preventing "cheating"; instead, now that there's some notion of beating the game by completing all its quests, I'd like to know how it easy it becomes to beat it by e.g. raising stats with a for loop.

**Comment by facundoolano** [comment]
I'm going to close this one since the were several changes in the game balance since this conversation started. Anyone feel free to open a new issue if you consider there's still room for improvement in this area.
