### ISSUE TITLE
Condensed output if rpg-cli is shared with other commands (and separators)

### ISSUE THREAD

**Issue by vatonbero** [facundoolano/rpg-cli#130]
Hi there,

Great idea you got here. I like it howver i want to propose 2 changes:

1. Condense output for us who want to use this neat game while doing our stuff on the system. I am using, for example, `cd` function to list directory right after changing location. This could lead to clutter in te terminal like: 

```
$ cd /usr/share/
     rat[7][xxxx][----]@/usr/share 
   thief[2][xxx-] -17hp 
     rat[7][xxxx] dodged!
   thief[2][x---] -13hp 
     rat[7][xxxx] dodged!
   thief[2][----] -14hp 
   thief[2][----] 💀
abrt                         gnome-packagekit       mobile-broadband-provider-info
accountsservice              gnome-session          ModemManager
aclocal                      gnome-settings-daemon  mousetweaks
adobe                        gnome-shell            mozilla
```
What if you introduce "slim output"? I dont know how it would be implemented right now but to show only enemy, if any, and then the outcome of the battle?

2. My second proposal is in direct relation to the 1st: add separators to be added after battle. Something like:
```
$ cd /usr/share/
     rat[7][xxxx][----]@/usr/share 
   thief[2][xxx-] -17hp 
     rat[7][xxxx] dodged!
   thief[2][x---] -13hp 
     rat[7][xxxx] dodged!
   thief[2][----] -14hp 
   thief[2][----] 💀
---------------------------------------------------------------------------------------------
abrt                         gnome-packagekit       mobile-broadband-provider-info
accountsservice              gnome-session          ModemManager
aclocal                      gnome-settings-daemon  mousetweaks
adobe                        gnome-shell            mozilla
```
Support for both top and/or bottom separator would be apprieciated.

**Comment by facundoolano** [comment]
Hi @vatonbero, thanks for the feedback. As a general note, one of the goals I had for the program is to make it flexible enough to accommodate different output preferences, without adding to much complexity to the code. Where possible I think it's preferable to push the customization to the shell layer rather than adding options to the Rust program.

Have you checked the shell integration guide? Particularly the [low-level commands section](https://github.com/facundoolano/rpg-cli/tree/7dd7c4b61f8b80c27652aab0f9489a213c71bee5/shell#low-level-commands). The `--quiet` option can be used for the `cd` subcommand (I realize now that this isn't very clear from that doc) to achieve something like what you propose in (1): display enemy appearence and battle outcome and omitting the intermediate battle turns. Can you try that and let me know if you think it's current behavior could be improved (the output changed a lot since I added that flag, and perhaps it became more verbose than it should).

Regarding (2) that sounds like something that could be achieved by extra code in your shell wrapper function. You could perhaps capture the command output, and if it's non empty add the separator.

**Comment by vatonbero** [comment]
Thank you for quick response.

> the output changed a lot since I added that flag, and perhaps it became more verbose than it should
The first thing i checked is shell integration and I think that verbosity here is the issue since i have the following output right now:

```
$ rpg-cli --quiet
thief[1]	@home	hp:27/34	mp:0/0	xp:25/30	att:0	mag:7	def:0	spd:
21	equip:{}	item:{}	g:57
```
Now this is when you call `--plain` and `--quiet`. I get what i want with `--quiet`, thank you. This might raise different question: i was under impression that `--plain` will strip emojis from output. Help is not stating that so i might be wrong here.

I guess wat i wanted to accomplish is `--quiet` without emojis. Sorry for the confusion! 

> Regarding (2) that sounds like something that could be achieved by extra code in your shell wrapper function. You could perhaps capture the command output, and if it's non empty add the separator.

Correct! I was wondeing if there is a way to do this in program directly so we could avoid command line foo. I can check some ways to do that and adding this to the document might help puerly to avoid calling something multiple times and making checks... complicated.

**Comment by facundoolano** [comment]
> I guess wat i wanted to accomplish is --quiet without emojis. Sorry for the confusion!

When you say emojis you mean uncide emojis like ✨ and 🔥 or you mean ascii symbols like used in `thief[1]` and `item:{}`? 

The basic idea is quiet = less verbose, plain = easier to parse by other programs/scripts, but as noted the current behavior may not be the best to achieve those specific goals, so if you have concrete improvement suggestions feel free to send them (preferably as separate issues).

**Comment by vatonbero** [comment]
> When you say emojis you mean unicode emojis like :sparkles: and :fire: or you mean ascii symbols like used in `thief[1]` and `item:{}`?

Yes, i was under impression that `--plain` will replace emojis with ascii and not change anything else.

We can close this issue since i i got all the answers however i will open new ones if that is needed. Thank you very much!
