### ISSUE TITLE
No output printed when not changing directories

### ISSUE THREAD

**Issue by dmuth** [facundoolano/rpg-cli#32]
Version: 0.2.0, OS/X binary

Hi!  I saw this on Hacker News, it looks neat, and I wanted play around with it.

Something I wanted to offer feedback on is that I had trouble understanding the flow at first, because the app doesn't print anything when you don't change directories.  Example:

```
$ rpg-cli rpg/

   slime[1][xxxx]@~/tmp/rpg 

   slime[1][xxxx] -8hp
   slime[1][xxxx] -8hp
[snip]
   slime[1][----] -12hp

    hero[3][xxxx][x---]@~/tmp/rpg +111xp ++level +114g

$ rpg-cli $HOME

    hero[3][xxxx][x---]@home +8hp

$ rpg-cli $HOME
$
```

The second time I ran `rpg-cli $HOME`, my character obviously didn't change directories, and while with the benefit of hindsight, I can understand why output wasn't printed, it still confused me when I first started playing this, and I thought I may have been doing something incorrectly.

Expected behavior from running `rpg-cli $HOME` a second time (or for any directory, tbh) would be to print the here's location and stats.

Thanks for reading!

-- Doug

**Comment by facundoolano** [comment]
Thanks, this sort UX feedback is very much appreciated.

I understand how no output can be confusing depending on the user expectations, but I'm leaning more towards the program working like a `cd` replacement, in which case I think it makes sense that there's no output when you send the hero to the same place it already is ("When a program has nothing surprising to say, it should say nothing").

As a note, it's not only when you don't change directories that there's no output, but whenever nothing changes after a movement. E.g. if you did `rpg-cli rpg/` and there wasn't an enemy  appearing in the new directory, there wouldn't be output; likewise, the first return to home you show printed a status because hp was restored, but if you go went back home with full hp, nothing would be printed either.

**Comment by HaQadosch** [comment]
Any chance to have an optional verbose mode?

**Comment by facundoolano** [comment]
yeah I'm planning on verbosity levels, maybe something like this

* 0: completely silent
* 1: always print a line of general status (location, basic stats). this is aimed to be consumed by other programs, for example as proposed in #19 
* 2: something human readable / prettier, similar to the current default

I suppose I could either add an extra level 3 or just update level 2 to match what we request here, to always print some status after a command runs, regardless of whether there was some noteworthy event.

**Comment by dmuth** [comment]
I think those verbosity levels sound great!

**Comment by facundoolano** [comment]
Reopening this until I incorporate the verbosity levels, since the output on all commands by default wasn't playing well with the `cd` replacement.

**Comment by facundoolano** [comment]
This should now be possible by calling `rpg-cli -q` after moving, for example:

```sh
rpg () {
    rpg-cli cd "$@"
    rpg-cli -q    
}
```
