### ISSUE TITLE
Datafile upgrade

### ISSUE THREAD

**Issue by rouben** [facundoolano/rpg-cli#94]
Hi, I have an old install of rpg-cli 0.2.0. When updgrading to latest release 0.6.0, I get a segfault when trying to read the datafile. I assume that's because its format has changed.

Is there any way to update the data, or is my only choice to reset the game and lose my character?

**Comment by facundoolano** [comment]
Hey @rouben . Sorry about that, but there have been many changes since 0.2.0. Among those are changes in stats and new items, so I'm not sure v0.2 stats would be balanced with the latest version even if file is properly parsed.

If you still want to give it a try, there are a couple of things you can do (make sure to backup `~/.rpg/data`):

* take note of your character stats/items, then `rpg reset --hard` to remove the file. The new version uses JSON for the datafile, so you can manually edit `~/.rpg/data` and set back the stats to what you had before
* alternatively, try to upgrade to each intermediate version (e.g. install v0.3.0, run the game so the file gets updated, then v0.4.0, v0.4.1 (this is where the file format changed to JSON), etc.). Not sure if this going to work since I didn't check for all possibly breaking changes in v0.6.0 😬 

Let me know if any of that worked

**Comment by rouben** [comment]
Thank you so much for your kind and detailed reply. I ended up doing as you suggested; just manually edited the datafile JSON fields to match my previous character.

Out of curiosity I'll try the incremental upgrade approach as well.

Thanks again for your help and suggestions!

**Comment by facundoolano** [comment]
Closing this issue, comment if you have any updates or need further help.
